# Generated by Django 3.1 on 2023-03-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desctiption',
            new_name='description',
        ),
    ]
